name: Run Lindy Automation (Cookie Auth)

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9 AM UTC
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
          playwright install-deps chromium
      
      - name: Restore Google cookies
        run: |
          echo "${{ secrets.GOOGLE_COOKIES }}" | base64 -d > google_cookies.json
      
      - name: Run automation
        run: |
          python main_playwright_cookies.py
      
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-results
          path: |
            *.log
            *.png
          retention-days: 7
